# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsAnswerer', to='main_app.User'),
        ),
    ]
