# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190827_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Does This Work', max_length=100),
            preserve_default=False,
        ),
    ]
